### ISSUE TITLE
Movie search not working

### ISSUE THREAD

**Issue by luispedrofonseca** [DONSA/alfred-iris#1]
I get this error when performing a search:

```
[2017-10-10 14:56:08][ERROR: input.scriptfilter] Code 1: /Volumes/Data/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.CD3AE40B-978A-4898-849E-E436B416B773/main.js:29
            if (movies.length)
                      ^

TypeError: Cannot read property 'length' of undefined
    at /Volumes/Data/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.CD3AE40B-978A-4898-849E-E436B416B773/main.js:29:23
    at /Volumes/Data/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.CD3AE40B-978A-4898-849E-E436B416B773/node_modules/omdb/index.js:126:20
    at done (/Volumes/Data/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.CD3AE40B-978A-4898-849E-E436B416B773/node_modules/needle/lib/needle.js:377:14)
    at PassThrough.<anonymous> (/Volumes/Data/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.CD3AE40B-978A-4898-849E-E436B416B773/node_modules/needle/lib/needle.js:576:9)
    at emitNone (events.js:110:20)
    at PassThrough.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Searching and downloading subtitles works fine though.

Any idea what might be going on?

**Comment by DONSA** [comment]
OMDb now requires API key:

> New API Keys! Due to some security concerns on how the keys were being distributed I updated the form to email them and also changed the algorithm used, which means your older keys not obtained through email will eventually stop working.

I requested one now.

**Comment by DONSA** [comment]
This was fixed in the latest commit. I've also updated the README.md.
Let me know if you need any help.
